services:
    # always have shade-agent-api first in order of services
    shade-agent-api:
        environment:
            NEAR_ACCOUNT_ID: ${NEAR_ACCOUNT_ID}
            NEAR_SEED_PHRASE: ${NEAR_SEED_PHRASE}
            DEPLOY_CONTRACT: ${DEPLOY_CONTRACT}
            API_CODEHASH: ${API_CODEHASH}
            APP_CODEHASH: ${APP_CODEHASH}
            ENTROPY: ${ENTROPY}
            NEXT_PUBLIC_contractId: ${NEXT_PUBLIC_contractId}
            SHADE_AGENT_PORT: ${SHADE_AGENT_PORT}
        platform: linux/amd64 # Explicitly set for TDX
        # shade-agent-api-image
        image: mattdlockyer/shade-agent-api@sha256:1eb4e9a1544add8c6b8f2f0bf857b58f730742cf48829fbfdff6b7ba97e9b95b
        container_name: shade-agent-api
        ports:
            - '3140:3140'
        volumes:
            - /var/run/tappd.sock:/var/run/tappd.sock
        restart: always
    shade-agent-api-test:
        platform: linux/amd64 # Explicitly set for TDX
        # shade-agent-app-image
        image: mattdlockyer/shade-agent-api-test@sha256:ca2c6a121674ab079cb74e8ff80a190f8aec2845460af950b76587c1e9064f32
        container_name: shade-agent-api-test
        ports:
            - '3000:3000'
        volumes:
            - /var/run/tappd.sock:/var/run/tappd.sock
        restart: always
