services:
    # always have shade-agent-api first in order of services
    shade-agent-api:
        environment:
            NEAR_ACCOUNT_ID: ${NEAR_ACCOUNT_ID}
            NEAR_SEED_PHRASE: ${NEAR_SEED_PHRASE}
            API_CODEHASH: ${API_CODEHASH}
            APP_CODEHASH: ${APP_CODEHASH}
            NEXT_PUBLIC_contractId: ${NEXT_PUBLIC_contractId}
            NEAR_RPC_JSON: ${NEAR_RPC_JSON}
        platform: linux/amd64 # Explicitly set for TDX
        # shade-agent-api-image
        image: mattdlockyer/shade-agent-api@sha256:d021bcb4866aa63613bf5d08a4b8f0154ca32a8daeee0227acc0f868e289b6e2
        container_name: shade-agent-api
        volumes:
            - /var/run/tappd.sock:/var/run/tappd.sock
        restart: always
    shade-agent-api-test:
        environment:
            NEXT_PUBLIC_contractId: ${NEXT_PUBLIC_contractId}
            NEAR_RPC_JSON: ${NEAR_RPC_JSON}
            SHADE_AGENT_PORT: 3000
            INCLUDE_TESTS: 'true'
            NO_BOOT: 'true'
        platform: linux/amd64 # Explicitly set for TDX
        # shade-agent-app-image
        image: mattdlockyer/shade-agent-api@sha256:d021bcb4866aa63613bf5d08a4b8f0154ca32a8daeee0227acc0f868e289b6e2
        container_name: shade-agent-api-test
        ports:
            - '3000:3000'
        volumes:
            - /var/run/tappd.sock:/var/run/tappd.sock
        restart: always
